name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia às 00:00
  workflow_dispatch:      # permite rodar manualmente também

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.METRICS_TOKEN }}
          
          user: felipereira10
          template: classic
          base: header, repositories
          config_timezone: America/Sao_Paulo

          plugin_languages: yes
          plugin_languages_indepth: no
          plugin_languages_threshold: 2%
